backend/modules/page/models/Category.php
<?php

namespace backend\modules\page\models;

use common\helpers\SitemapHelper;
use Yii;
use backend\modules\page\models\CategoryLang;
use yii\behaviors\SluggableBehavior;
use backend\modules\transliterator\services\TransliteratorService;
use backend\modules\seo\models\Seo;

class Category extends \yii\db\ActiveRecord
{

    const ACTIVE_YES = 1;
    const ACTIVE_NO = 0;
    const ALIAS_CATEGORY_MAINROLES = 'mainroles';

    public static function tableName()
    {
        return 'page_category';
    }

    public function rules()
    {
        return [
            [['parent_id', 'active'], 'integer'],
            [['alias'], 'string', 'max' => 128],
            [['alias'], 'unique'],
            ['alias', 'match', 'pattern' => '/[a-zA-Z0-9-_.]+$/',
                'message' => Yii::t('common', 'Field must contain only latin letters, digits, spaces and hyphens')],
            [['alias', 'parent_id'], 'default', 'value' => null]
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => Yii::t('page', 'Parent category'),
            'alias' => 'Alias',
            'active' => Yii::t('page', 'Active'),
        ];
    }

    public function getLang()
    {
        return $this->hasOne(CategoryLang::className(), ['category_id' => 'id'])
            ->where(['lang' => \Yii::$app->language]);
    }

    public function getTitle()
    {
        return $this->lang ? $this->lang->title : '';
    }

    public function getSeo()
    {
        return $this->hasOne(Seo::className(), ['record_id' => 'id'])->where(['table_name' => $this::tableName()]);
    }

    public function getParent()
    {
        return $this->hasOne($this::className(), ['id' => 'parent_id'])
            ->joinWith('lang');
    }

    public function getSubcategories()
    {
        return $this->hasMany($this::className(), ['parent_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->alias = TransliteratorService::transliterate($this->alias);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        CategoryLang::deleteAll(['category_id' => $this->primaryKey]);
        self::deleteAll(['parent_id' => $this->primaryKey]);
        Page::deleteAll(['category_id' => $this->primaryKey]);
        Seo::deleteAll(['table_name' => $this::tableName(), 'record_id' => $this->primaryKey]);
    }
}

backend/modules/page/controllers/CategoryController.php
<?php

namespace backend\modules\page\controllers;

use backend\modules\accesscontrol\AccessControlFilter;
use backend\modules\seo\models\Seo;
use backend\modules\seo\models\SeoLang;
use Yii;
use backend\modules\page\models\CategoryLang;
use yii\base\Model;
use yii\behaviors\SluggableBehavior;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use backend\modules\page\models\Page;
use backend\modules\page\models\Category;
use yii\web\NotFoundHttpException;
use backend\modules\transliterator\services\TransliteratorService;


class CategoryController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControlFilter::className(),
            ]
        ];
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Category::find()
                ->where(['parent_id' => null])
        ]);

        return $this->render('index', [
            'data' => $dataProvider
        ]);
    }

    public function actionCreate()
    {
        $model = new Category();
        $modelLang = new CategoryLang();
        $modelLang->lang = Yii::$app->language;

        $parentId = Yii::$app->request->get('parent');
        if ($parentId) {
            $parent = $this->findCategory($parentId);
            $model->parent_id = $parent->primaryKey;
        }

        if ($model->load(Yii::$app->request->post()) && $modelLang->load(Yii::$app->request->post())) {
            if (!$model->alias) {
                $model->alias = TransliteratorService::transliterate($modelLang->title);
            }

            $modelLang->category_id = 0;

            if (Model::validateMultiple([$model, $modelLang]) && $model->save()) {
                $modelLang->category_id = $model->primaryKey;
                $modelLang->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'modelLang' => $modelLang
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => Category::findOne($id),
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findCategory($id);

        $modelLang = $model->lang;
        if (!$modelLang) {
            $modelLang = new CategoryLang();
            $modelLang->category_id = $model->primaryKey;
            $modelLang->lang = Yii::$app->language;
        }

        if ($model->load(Yii::$app->request->post()) && $modelLang->load(Yii::$app->request->post())) {
            if (!$model->alias) {
                if ($modelLang->lang == 'ru') {
                    $model->alias = TransliteratorService::transliterate($modelLang->title);
                } else {
                    $modelLangForAlias = CategoryLang::find()
                        ->where(['category_id' => $model->primaryKey, 'lang' => 'ru'])
                        ->one();

                    if ($modelLangForAlias) {
                        $model->alias = TransliteratorService::transliterate($modelLangForAlias->title);
                    }
                }
            }

            if (Model::validateMultiple([$model, $modelLang]) && $model->save() && $modelLang->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'modelLang' => $modelLang
        ]);
    }

    public function actionDelete($id)
    {
        $category = $this->findCategory($id);
        $category->delete();

        return $this->redirect(['index']);
    }

    public function actionSeo($id)
    {
        $model = $this->findCategory($id);

        $seo = $model->seo;
        if (!$seo) {
            $seo = new Seo();
            $seo->table_name = $model::tableName();
            $seo->record_id = $model->primaryKey;
            $seo->save();
        }

        $seoLang = $seo->lang;
        if (!$seoLang) {
            $seoLang = new SeoLang();
            $seoLang->seo_id = $seo->primaryKey;
            $seoLang->lang = Yii::$app->language;
            $seoLang->save();
        }

        if ($seoLang->load(Yii::$app->request->post()) && $seoLang->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('seo', [
            'model' => $model,
            'seo' => $seo,
            'seoLang' => $seoLang
        ]);
    }

    private function findCategory($id)
    {
        $model = Category::findOne($id);

        if (!$model) {
            throw new NotFoundHttpException('Category not found.');
        }

        return $model;
    }
}

backend/modules/page/controllers/PageController.php
<?php

namespace backend\modules\page\controllers;

use backend\modules\accesscontrol\AccessControlFilter;
use backend\modules\page\models\PageLang;
use backend\modules\page\models\PageSearch;
use backend\modules\seo\models\SeoLang;
use Yii;
use yii\base\Model;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use backend\modules\page\models\Page;
use backend\modules\page\models\Category;
use yii\web\NotFoundHttpException;
use backend\modules\seo\models\Seo;
use backend\modules\transliterator\services\TransliteratorService;

class PageController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControlFilter::className(),
            ]
        ];
    }

    public function actionIndex($id = null)
    {
        $searchModel = new PageSearch();

        $params = Yii::$app->request->queryParams;

        if ($id && !isset(Yii::$app->request->queryParams['PageSearch'])) {
            $params['PageSearch']['category_id'] = (int)$id;
        }

        $dataProvider = $searchModel->search($params);
        $category = $searchModel->category_id ? $this->findCategory($searchModel->category_id) : null;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'category' => $category
        ]);
    }

    public function actionCreate()
    {
        $model = new Page();
        $modelLang = new PageLang();
        $modelLang->lang = Yii::$app->language;

        $categoryId = Yii::$app->request->get('category');
        $category = $categoryId ? $this->findCategory($categoryId) : null;
        $model->category_id = $categoryId;

        if ($model->load(Yii::$app->request->post()) && $modelLang->load(Yii::$app->request->post())) {
            if (!$model->alias) {
                $model->alias = TransliteratorService::transliterate($modelLang->title);
            }

            $modelLang->page_id = 0;

            if (Model::validateMultiple([$model, $modelLang]) && $model->save()) {
                $modelLang->page_id = $model->primaryKey;
                $modelLang->save();

                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'modelLang' => $modelLang,
            'category' => $category
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findPage($id)
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findPage($id);

        $modelLang = $model->lang;
        if (!$modelLang) {
            $modelLang = new PageLang();
            $modelLang->page_id = $model->primaryKey;
            $modelLang->lang = Yii::$app->language;
        }

        if ($model->load(Yii::$app->request->post()) && $modelLang->load(Yii::$app->request->post())) {
            if (!$model->alias) {
                $model->alias = TransliteratorService::transliterate($modelLang->title);
            }

            if (Model::validateMultiple([$model, $modelLang]) && $model->save() && $modelLang->save()) {
                return $this->redirect(['view', 'id' => $model->primaryKey]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'modelLang' => $modelLang
        ]);
    }

    public function actionSeo($id)
    {
        $model = $this->findPage($id);

        $seo = $model->seo;
        if (!$seo) {
            $seo = new Seo();
            $seo->table_name = $model::tableName();
            $seo->record_id = $model->primaryKey;
            $seo->save();
        }

        $seoLang = $seo->lang;
        if (!$seoLang) {
            $seoLang = new SeoLang();
            $seoLang->seo_id = $seo->primaryKey;
            $seoLang->lang = Yii::$app->language;
            $seoLang->save();
        }

        if ($seoLang->load(Yii::$app->request->post()) && $seoLang->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('seo', [
            'model' => $model,
            'seo' => $seo,
            'seoLang' => $seoLang
        ]);
    }

    private function findPage($id)
    {
        $model = Page::findOne($id);

        if (!$model) {
            throw new NotFoundHttpException('Page not found.');
        }

        return $model;
    }

    private function findCategory($id)
    {
        $category = Category::findOne($id);

        if (!$category) {
            throw new NotFoundHttpException('Category not found.');
        }

        return $category;
    }

    public function actionDelete($id)
    {
        $category = $this->findPage($id);
        $category->delete();

        return $this->redirect(['index']);
    }
}

backend/modules/page/views/category/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use backend\modules\page\models\Category;
?>

<div class="rubric-form">
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($modelLang, 'title') ?>
    <?= $form->field($model, 'alias') ?>
    <?= $form->field($model, 'active')->dropDownList(array(
        Category::ACTIVE_YES => Yii::t('common', 'Yes'),
        Category::ACTIVE_NO => Yii::t('common', 'No')
    )); ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('common', 'Create') : Yii::t('common', 'Save'), [
                'class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary'
        ]) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/modules/page/views/category/_submenu.php
<?php
use yii\helpers\Url;
use yii\bootstrap\Html;

$action = Yii::$app->controller->action->id;
if ($action == 'update') {
    $this->title = Yii::t('page', 'Category updating') . ' "' . $model->title . '"';
} elseif ($action == 'seo') {
    $this->title = Yii::t('page', 'Category SEO updating') . ' "' . $model->title . '"';
}
$this->params['breadcrumbs'][] = $this->title;
?>

<h1><?= Html::encode($this->title) ?></h1>

<ul class="nav nav-tabs">
    <li <?= ($action === 'update') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to(['update', 'id' => $model->primaryKey]) ?>">
            <?= Yii::t('common', 'Editing'); ?>
        </a>
    </li>
    <li <?= ($action === 'seo') ? 'class="active"' : '' ?>>
        <a href="<?= Url::to(['seo', 'id' => $model->primaryKey]) ?>">
            SEO
        </a>
    </li>
</ul>
<br>

backend/modules/page/views/category/create.php
<?php

use yii\helpers\Html;

$this->title = Yii::t('page', 'Create page category');
$this->params['breadcrumbs'][] = ['label' => Yii::t('page', 'Categories list'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="rubric-create">
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'modelLang' => $modelLang
    ]) ?>
</div>

backend/modules/page/views/category/index.php
<?php
use yii\helpers\Url;
use backend\modules\page\models\Category;

$this->title = Yii::t('page', 'Categories list');
?>

<div class="rubric-default-index">
    <h1>
        <?= $this->title; ?>
        <a href="<?= Url::to(['create']); ?>" class="btn btn-primary block right">
            <?= Yii::t('page', 'Add category'); ?>
        </a>
    </h1>

    <table class="table table-bordered" style="margin-top: 15px;">
        <thead>
        <tr>
            <th width="60">ID</th>
            <th><?= Yii::t('page', 'Title'); ?></th>
            <th><?= Yii::t('page', 'Subcategories'); ?></th>
            <th width="75"><?= Yii::t('page', 'Active'); ?></th>
            <th width="130"><?= Yii::t('common', 'Actions'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($data->models as $model) { ?>
            <tr>
                <td><?= $model->primaryKey; ?></td>
                <td>
                    <a href="<?= Url::to(['view', 'id' => $model->primaryKey]); ?>">
                        <?= $model->title; ?>
                    </a>
                </td>
                <td>
                    <?php $subcategories = $model->subcategories; ?>
                    <?php if ($subcategories) { ?>
                        <?php foreach ($subcategories as $subcategory) { ?>
                            <a href="<?= Url::to(['view', 'id' => $subcategory->primaryKey]); ?>" class="block">
                                <?= $subcategory->title; ?>
                            </a>
                        <?php } ?>
                    <?php } else { ?>
                        &nbsp;
                    <?php } ?>
                </td>
                <td>
                    <?= $model->active == Category::ACTIVE_YES ? Yii::t('common', 'Yes') : Yii::t('common', 'No'); ?>
                </td>
                <td>
                    <a href="<?= Url::to(['view', 'id' => $model->primaryKey]); ?>"
                       title="<?= Yii::t('common', 'View'); ?>"
                       class="btn btn-default btn-sm"
                    >
                        <span class="glyphicon glyphicon-eye-open"></span>
                    </a>
                    <a href="<?= Url::to(['update', 'id' => $model->primaryKey]); ?>"
                       title="<?= Yii::t('common', 'Edit'); ?>"
                       class="btn btn-default btn-sm"
                    >
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                    <a href="<?= Url::to(['delete', 'id' => $model->primaryKey]); ?>"
                       title="<?= Yii::t('common', 'Delete'); ?>"
                       class="btn btn-default btn-sm"
                       onclick="return confirm('<?= Yii::t('common', 'Are you sure you want to delete this item?'); ?>')"
                    >
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>

backend/modules/page/views/category/seo.php
<?php
use backend\widgets\SeoWidget;

$this->params['breadcrumbs'][] = ['label' => Yii::t('page', 'Categories list'), 'url' => ['index']];
?>

<div class="rubric-create">
    <?= $this->render('_submenu', [
        'model' => $model
    ]); ?>

    <?= SeoWidget::widget([
        'model' => $seo,
        'parameters' => ['modelLang' => $seoLang]
    ]); ?>
</div>

backend/modules/page/views/category/update.php
<?php
$this->params['breadcrumbs'][] = ['label' => Yii::t('page', 'Categories list'), 'url' => ['index']];
?>

<div class="rubric-create">
    <?= $this->render('_submenu', [
        'model' => $model,
        'modelLang' => $modelLang
    ]); ?>

    <?= $this->render('_form', [
        'model' => $model,
        'modelLang' => $modelLang
    ]) ?>
</div>

backend/modules/page/views/category/view.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use backend\modules\page\models\Page;

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('page', 'Categories list'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rubric-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('page', 'Add page'), ['page/create', 'category' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('common', 'Edit'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('common', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('common', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>

        <a href="<?= Url::to(['create', 'parent' => $model->primaryKey]); ?>" class="btn btn-primary" style="float: right">
            <?= Yii::t('page', 'Add subcategory'); ?>
        </a>
    </p>

    <table id="w0" class="table table-striped table-bordered detail-view">
        <tbody>
        <tr>
            <th width="200px">ID</th>
            <td><?= $model->primaryKey; ?></td>
        </tr>
        <tr>
            <th><?= Yii::t('page', 'Title'); ?></th>
            <td><?= $model->title; ?></td>
        </tr>
        <tr>
            <th>Alias</th>
            <td><?= $model->alias; ?></td>
        </tr>
        <tr>
            <th><?= Yii::t('page', 'Parent category'); ?></th>
            <td>
                <?php $parent = $model->parent; ?>
                <?php if ($parent) { ?>
                    <a href="<?= Url::to(['view', 'id' => $parent->primaryKey]) ?>"><?= $parent->title; ?></a>
                <?php } ?>
            </td>
        </tr>
        <tr>
            <th><?= Yii::t('page', 'Subcategories'); ?></th>
            <td>
                <?php $subcategories = $model->subcategories; ?>
                <?php foreach ($subcategories as $subcategory) { ?>
                    <a href="<?= Url::to(['view', 'id' => $subcategory->primaryKey]); ?>" class="block">
                        <?= $subcategory->title; ?>
                    </a>
                <?php } ?>

                <div style="margin-top: 10px">
                    <a href="<?= Url::to(['create', 'parent' => $model->primaryKey]); ?>"
                       class="btn-sm btn-success without-hover-text-decoration"
                    >
                        <?= Yii::t('news', 'Add subcategory'); ?>
                    </a>
                </div>
            </td>
        </tr>
        <tr>
            <th><?= Yii::t('page', 'Pages'); ?></th>
            <td>
                <a href="<?= Url::to(['page/index', 'id' => $model->primaryKey]); ?>">
                    <?= Yii::t('page', 'Pages'); ?>
                    (<?= Page::find()->where(['category_id' => $model->primaryKey])->count(); ?>)
                </a>
            </td>
        </tr>
        </tbody>
    </table>
</div>