frontend/modules/instruments/controllers/DefaultController.php
<?php

namespace frontend\modules\instruments\controllers;

use backend\modules\page\models\Page;
use backend\modules\page\models\Category as PageCategory;
use yii\web\Controller;
use backend\modules\instrument\models\Instrument;

class DefaultController extends Controller
{

    public function actionIndex()
    {
        $models = Instrument::find()
            ->innerJoin('instrument_visibility', 'instrument.id = instrument_visibility.instrument_id')
            ->where(['in', 'instrument_visibility.type_id', \Yii::$app->userRole->role])
            ->andWhere(['type' => Instrument::TYPE_INSTRUMENT])
            ->andWhere('parent_id IS NULL')
            ->orderBy('position')
            ->all();

        return $this->render('index', ['models' => $models]);
    }
}

frontend/modules/instruments/controllers/ElevatorsController.php
<?php

namespace frontend\modules\instruments\controllers;

use backend\modules\elevator\models\Elevator;
use backend\modules\elevator\models\ElevatorAccessibility;
use common\helpers\GoogleMapsApiHelper;
use frontend\modules\instruments\models\InstrumentGet;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use frontend\modules\instruments\models\ElevatorSearch;
use Yii;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\web\NotFoundHttpException;

class ElevatorsController extends Controller
{
    public $googleMapsApiHelper;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->googleMapsApiHelper = new GoogleMapsApiHelper();
    }

    public function actionMap()
    {
        $instrumentGet = new InstrumentGet(4);
        $instrument = $instrumentGet->searchOne(Yii::$app->request->get('company_type'));

        if ($instrument['status'] == InstrumentGet::STATUS_NO_ACCCES) {
            return $this->redirect(['/instruments/instrument/no-access', 'id' => $instrumentGet->instrument_id ]);
        }

        $searchModel = new ElevatorSearch();
        $queryParams = Yii::$app->request->queryParams;
        $query = $searchModel->search($queryParams);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false
        ]);

        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->groupBy('id')->count(),
            'pageSize' => 10
        ]);

        $locations = $this->buildMarkersArray($dataProvider->getModels(),
            isset($queryParams['ElevatorSearch']) ? $queryParams['ElevatorSearch'] : []);

        $models = $query->offset($pages->offset)->limit($pages->limit)->all();

        return $this->render('map', [
            'searchModel' => $searchModel,
            'pages' => $pages,
            'locations' => $locations,
            'models' => $models,
            'instrument' => $instrument
        ]);
    }

    public function actionView($alias = NULL, $id = NULL)
    {
        if ($id) {
            $model = Elevator::find()->where([Elevator::tableName().'.id' => $id])->joinWith('lang')->one();
            if ($model !== null) {
                return $this->redirect(['/instruments/elevators/view/'.$model->alias],  301);
            } else {
                throw new NotFoundHttpException('The requested page does not exist.');
            }
        }

        $model = $this->findModel($alias);
        $locations = $this->buildMarker($model);

        return $this->render('view', [
            'model' => $model,
            'locations' => $locations
        ]);
    }

    private function buildMarker(Elevator $elevator)
    {
        if (!$elevator->coordinates || $elevator->address_confirmed != Elevator::ADDRESS_CONFIRMED_YES) {
            return 'false';
        }

        $coordinates = explode(',',$elevator->coordinates);
        $locations = "[";

        $content = "<div class=\"marker\">";
        $content .= "<div class=\"marker-title\">$elevator->title</div>";
        $content .= "<div>$elevator->address</div>";
        if ($elevator->loading) {
            $content .= "<div>".Yii::t('elevator', 'Elevator loading').": $elevator->loading т</div>";
        }
        if ($elevator->unloading) {
            $content .= "<div>".Yii::t('elevator', 'Elevator unloading').": $elevator->unloading т</div>";
        }

        $content .= '</div>';
        $locations .= "['".$content."',".$coordinates[0].",".$coordinates[1]."]";
        $locations .= "]";

        return $locations;
    }

    public function buildMarkersArray($models, $params)
    {
        $fromLocationString = isset($params['from_location']) ? $params['from_location'] : '';
        $loadingTranslates = Yii::t('elevator', 'Elevator loading');
        $unloadingTranslates = Yii::t('elevator', 'Elevator unloading');
        $warehouseTranslates = Yii::t('elevator', 'Warehouses');
        $detailTranslates = Yii::t('common', 'Detail');
        $distanseTranslates = Yii::t('elevator', 'Distance');
        $fromLocation = $fromLocationString ? $this->googleMapsApiHelper->getLocationByAddress($fromLocationString) : null;

        $locations = [];

        if ($fromLocation) {
            $locations[] = [
                'coordinates' => [
                    'lat' => $fromLocation['lat'],
                    'lng' => $fromLocation['lng']
                ],
                'content' => "<div class=\"marker\"><div class=\"marker-title\">$fromLocationString</div></div>",
                'icon' => null,
                'title' => $fromLocationString
            ];
        }

        foreach ($models as $key => $elevator) {
            $coordinates = explode(',',$elevator->coordinates);
            $content = "<div class=\"marker\">";
            $content .= "<div class=\"marker-title\" style='margin-bottom: 5px;'>".str_replace("'","\\'",$elevator->title)."</div>";
            $content .= "<div style='margin-bottom: 5px;'>".str_replace("'","\\'",$elevator->address)."</div>";

            $accessibilities = $elevator->accessibilities;
            if ($accessibilities) {
                $images = '';
                foreach ($accessibilities as $accessibility) {
                    if ($accessibility->accessibility_id == ElevatorAccessibility::ACCESS_BY_CAR) {
                        $images .= Html::img('/images/auto.png', ['width' => 40, 'title' => Yii::t('elevator', 'Access by car')]);
                    } elseif ($accessibility->accessibility_id == ElevatorAccessibility::ACCESS_BY_TRAIN) {
                        $images .= Html::img('/images/zd.png', ['width' => 40, 'title' => Yii::t('elevator', 'Access by train')]);
                    } elseif ($accessibility->accessibility_id == ElevatorAccessibility::ACCESS_BY_BOAT) {
                        $images .= Html::img('/images/water.png', ['width' => 40, 'title' => Yii::t('elevator', 'Access by boat')]);
                    }
                }

                if ($images) {
                    $content .= "<div style='margin-bottom: 5px;'>".$images."</div>";
                }
            }

            if ($elevator->volume) {
                $content .= "<div>$warehouseTranslates: $elevator->volume т</div>";
            }
            if ($elevator->loading) {
                $content .= "<div>$loadingTranslates: $elevator->loading т</div>";
            }
            if ($elevator->unloading) {
                $content .= "<div>$unloadingTranslates: $elevator->unloading т</div>";
            }

            $content .= "</div>";

            $locations[] = [
                'coordinates' => [
                    'lat' => $coordinates[0],
                    'lng' => $coordinates[1]
                ],
                'content' => $content,
                'icon' => $this->getImageByPropertyTypeAndVolume($elevator->property_type, $elevator->volume),
                'title' => $elevator->title,
                'linkBlock' => '<div style=\'margin-top: 5px; text-align: center\'>'.Html::a($detailTranslates, ['view', 'alias' => $elevator->alias]).'</div>',
                'distanceTranslates' => $distanseTranslates
            ];
        }

        return json_encode($locations);
    }

    protected function findModel($alias)
    {
        $model = Elevator::find()->where([Elevator::tableName().'.alias' => $alias])->joinWith('lang')->one();
        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    private function getImageByPropertyTypeAndVolume($property_type, $volume) {
        $color = 'orange';
        $size = '1';
        if ($property_type == '6') {
            $color = 'green';
        } elseif($property_type == '1') {
            $color = 'grey';
        }
        if ($volume > 100000) {
            $size = '3';
        } elseif ($volume >= 50000 && $volume < 100000) {
            $size = 2;
        }

        return '/images/marker_' . $size . '_' . $color . '.png';
    }
}

frontend/modules/instruments/views/elevators/_elevator.php
<?php
use backend\modules\elevator\models\ElevatorAccessibility;
use yii\helpers\Url;
use yii\helpers\StringHelper;
?>

<div class="sales-product elevator-block col-sm-12">
    <div class="col-sm-3 accessibilities-images-block">
        <?php $accessibilities = $model->accessibilities; ?>
        <?php foreach ($accessibilities as $one) { ?>
            <?php if ($one->accessibility_id == ElevatorAccessibility::ACCESS_BY_CAR) { ?>
                <img src="/images/auto.png" title="<?= Yii::t('elevator', 'Access by car'); ?>" alt="">
            <?php } elseif ($one->accessibility_id == ElevatorAccessibility::ACCESS_BY_TRAIN) { ?>
                <img src="/images/zd.png" title="<?= Yii::t('elevator', 'Access by train'); ?>" alt="">
            <?php } elseif ($one->accessibility_id == ElevatorAccessibility::ACCESS_BY_BOAT) { ?>
                <img src="/images/water.png" title="<?= Yii::t('elevator', 'Access by boat'); ?>" alt="">
            <?php } ?>
        <?php } ?>
    </div>
    <div class="col-sm-6 info-block" style="margin-top: 20px;">
        <a href="<?= Url::to(['view', 'alias' => $model->alias]); ?>">
            <?=StringHelper::truncate($model->title, 45, '...' )?>
        </a>
        <div class="location">
            <?php $location = $model->location; ?>
            <div title="<?= $location; ?>"><?= $location; ?></div>
            <?php if ($model->phones) { ?>
                <div><?= $model->phones; ?></div>
            <?php } ?>
            <?php if ($model->email) { ?>
                <div><?= $model->email; ?></div>
            <?php } ?>
        </div>
        <div style="padding-top: 15px">
            <a href="<?= Url::to(['view', 'alias' => $model->alias]); ?>" class="standart-link">
                <?= Yii::t('common', 'Detail'); ?>
            </a>
        </div>
    </div>
    <div class="col-sm-3 volumes-info-block" style="text-align: center">
        <span class="dsb">
            <?php $volume = $model->volume ? ($model->volume . ' т') : Yii::t('common', 'No data'); ?>
            <?= Yii::t('elevator', 'Warehouses'); ?>: <?= $volume; ?>
        </span>
        <span class="dsb">
            <?php $loading = $model->loading ? ($model->loading . ' '.Yii::t('elevator', 't\day')) : Yii::t('common', 'No data'); ?>
            <?= Yii::t('elevator', 'Elevator loading'); ?>: <?= $loading; ?>
        </span>
        <span class="dsb">
            <?php $unloading = $model->unloading ? ($model->unloading . ' '.Yii::t('elevator', 't\day')) : Yii::t('common', 'No data'); ?>
            <?= Yii::t('elevator', 'Elevator unloading'); ?>: <?= $unloading; ?>
        </span>
    </div>
</div>

frontend/modules/instruments/views/elevators/_left_filters.php
<?php
use backend\modules\commondata\models\Region;
use backend\modules\elevator\models\Elevator;
use backend\modules\elevator\models\ElevatorAccessibility;

$classname = \yii\helpers\StringHelper::basename(get_class($searchModel));
?>

<div class="col-sm-3 sidebar-grey left-filters" id="sidebar">
    <div class="sbbg" style="padding-top: 30px; padding-bottom: 30px;">
        <h4 class="sidebar-grey__title"><?= Yii::t('elevator', 'Warehouse volume'); ?>, т</h4>
        <div class="sidebar-grey-region">
            <div class="sidebar-grey-input col-sm-6">
                <?php echo $form->field($searchModel, 'volume_from')
                    ->textInput(['placeholder' => Yii::t('advertisement', 'From'), 'type' => 'number']
                    )->label(false);
                ?>
            </div>
            <div class="sidebar-grey-input col-sm-6">
                <?php echo $form->field($searchModel, 'volume_to')
                    ->textInput(['placeholder' => Yii::t('advertisement', 'To'), 'type' => 'number']
                    )->label(false);
                ?>
            </div>
            <div class="clearfix"></div>
        </div>

        <h4 class="sidebar-grey__title"><?= Yii::t('elevator', 'Elevator loading'); ?>, т</h4>
        <div class="sidebar-grey-region">
            <div class="sidebar-grey-input col-sm-6">
                <?php echo $form->field($searchModel, 'loading_from')
                    ->textInput(['placeholder' => Yii::t('advertisement', 'From'), 'type' => 'number']
                    )->label(false);
                ?>
            </div>
            <div class="sidebar-grey-input col-sm-6">
                <?php echo $form->field($searchModel, 'loading_to')
                    ->textInput(['placeholder' => Yii::t('advertisement', 'To'), 'type' => 'number']
                    )->label(false);
                ?>
            </div>
            <div class="clearfix"></div>
        </div>

        <h4 class="sidebar-grey__title"><?= Yii::t('elevator', 'Elevator unloading'); ?>, т</h4>
        <div class="sidebar-grey-region">
            <div class="sidebar-grey-input col-sm-6">
                <?php echo $form->field($searchModel, 'unloading_from')
                    ->textInput(['placeholder' => Yii::t('advertisement', 'From'), 'type' => 'number']
                    )->label(false);
                ?>
            </div>
            <div class="sidebar-grey-input col-sm-6">
                <?php echo $form->field($searchModel, 'unloading_to')
                    ->textInput(['placeholder' => Yii::t('advertisement', 'To'), 'type' => 'number']
                    )->label(false);
                ?>
            </div>
            <div class="clearfix"></div>
        </div>

        <h4 class="sidebar-grey__title" style="margin-top: 10px;"><?= Yii::t('elevator', 'Property type'); ?></h4>
        <div class="sidebar-grey-region">
            <?php $types = \backend\modules\elevator\models\Elevator::getPropertyTypes(); ?>
            <?php foreach ($types as $key => $type) { ?>
                <div class="sidebar-grey-input col-sm-12">
                    <input
                            type="checkbox"
                            id="type-<?= $key; ?>"
                            name="<?= $classname; ?>[type][]"
                            value="<?= $key; ?>"
                        <?= ($searchModel->type && in_array($key, $searchModel->type)) ? 'checked="checked"' : ''; ?>
                    >
                    <label for="type-<?= $key; ?>"><?= $type; ?></label>
                </div>
            <?php } ?>
            <div class="clearfix"></div>
        </div>

        <h4 class="sidebar-grey__title" style="margin-top: 20px;"><?= Yii::t('elevator', 'Laboratory'); ?></h4>
        <div class="sidebar-grey-region">
            <?php $laboratories = Elevator::getLaboratoriesList(); ?>
            <?php foreach ($laboratories as $key => $laboratory) { ?>
                <div class="sidebar-grey-input col-sm-12">
                    <input
                            type="checkbox"
                            id="laboratory-<?= $key; ?>"
                            name="<?= $classname; ?>[laboratory][]"
                            value="<?= $key; ?>"
                        <?= ($searchModel->laboratory && in_array($key, $searchModel->laboratory)) ? 'checked="checked"' : ''; ?>
                    >
                    <label for="laboratory-<?= $key; ?>"><?= $laboratory; ?></label>
                </div>
            <?php } ?>
            <div class="clearfix"></div>
        </div>

        <h4 class="sidebar-grey__title" style="margin-top: 20px;"><?= Yii::t('elevator', 'Accessibility'); ?></h4>
        <div class="sidebar-grey-region">
            <?php $accessibilities = ElevatorAccessibility::getTypes(); ?>
            <?php foreach ($accessibilities as $accessibility) { ?>
                <div class="sidebar-grey-input col-sm-12">
                    <input
                            type="checkbox"
                            id="accessibility-<?= $accessibility['id']; ?>"
                            name="<?= $classname; ?>[accessibility][]"
                            value="<?= $accessibility['id']; ?>"
                        <?= ($searchModel->accessibility && in_array($accessibility['id'], $searchModel->accessibility)) ? 'checked="checked"' : ''; ?>
                    >
                    <label for="accessibility-<?= $accessibility['id']; ?>"><?= $accessibility['title']; ?></label>
                </div>
            <?php } ?>
            <div class="clearfix"></div>
        </div>

        <h4 class="sidebar-grey__title reg" style="margin-top: 20px;"><?= Yii::t('common', 'Regions'); ?></h4>
        <div class="sidebar-grey-region">
            <?php $regions = Region::find()->joinWith('lang')->all(); ?>
            <?php foreach ($regions as $region) { ?>
                <div class="sidebar-grey-input col-sm-12">
                    <input
                            type="checkbox"
                            id="region-<?= $region->primaryKey; ?>"
                            name="<?= $classname; ?>[region][]"
                            value="<?= $region->primaryKey; ?>"
                        <?= ($searchModel->region && in_array($region->primaryKey, $searchModel->region)) ? 'checked="checked"' : ''; ?>
                    >
                    <label for="region-<?= $region->primaryKey; ?>"><?= $region->title; ?></label>
                </div>
            <?php } ?>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

frontend/modules/instruments/views/elevators/map.php
<?php
use yii\widgets\ActiveForm;
use backend\modules\commondata\models\City;
use kartik\widgets\Select2;
use yii\web\JsExpression;
use yii\helpers\ArrayHelper;
use backend\modules\elevator\models\Elevator;
use yii\bootstrap\Html;
use yii\helpers\Url;
use frontend\assets\ElevatorsMapAsset;
use yii\widgets\Breadcrumbs;
ElevatorsMapAsset::register($this);


$pageH1 = Yii::t('instruments', 'Elevators map');
$this->title = $pageH1 .' | '.Yii::$app->params['titlePrefix'];
$this->registerMetaTag(['name'=>'description', 'content'=> $pageH1.' | '.Yii::$app->params['descriptionPrefix']]);
$this->registerLinkTag(['rel' => 'canonical', 'href' => '/instruments/elevators/map']);
$this->params['breadcrumbs'][] = ['label' => Yii::t('instruments', 'Instruments'), 'url' => ['default/index']];
$this->params['breadcrumbs'][] = $pageH1;

$getCityUrl = \yii\helpers\Url::to(['/city-list/index']);
$classname = \yii\helpers\StringHelper::basename(get_class($searchModel));
?>

<div class="bread">
    <h1><?= $pageH1 ?></h1>
    <div class="bread-bg">
        <div class="container">
            <?= Breadcrumbs::widget(['links' => $this->params['breadcrumbs']]) ?>
        </div>
    </div>
</div>
<div class="container elevators-map-container">
    <div class="row">
        <?php $form = ActiveForm::begin(['method' => 'get', 'action' => Url::to(['map'])]); ?>
        <?= $this->render('_left_filters', ['form' => $form, 'searchModel' => $searchModel]); ?>

        <div class="col-sm-9 logistic-calc" data-content="page_content">
            <div class="col-xs-12 important-info">
                <img class="important-info__i" src="/images/important-i.png" alt="important-i">
                <img class="important-info__close" src="/images/important-close.png" alt="important-close">
                <img class="important-info__hide" src="/images/important-hide.png" alt="important-hide">
                <div class="important-info-content">
                    <p class="important-info__title"><?=Yii::t('instrument', 'Используются собранные в открытом доступе данные об элеваторах') ?></p>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-xs-12" style="padding-top: 20px;">
                    <?php echo $form->field($searchModel, 'name')->widget(Select2::classname(), [
                        'data' => ArrayHelper::map(Elevator::find()->joinWith('lang')->all(), 'title', 'title'),
                        'options' => [
                            'placeholder' => Yii::t('elevator', 'Title')
                        ],
                        'pluginOptions' => ['allowClear' => true]
                    ])->label(false); ?>

                    <?php $city = $searchModel->city_id ? City::find()
                        ->where([City::tableName().'.id' => $searchModel->city_id])
                        ->joinWith('region')
                        ->one() : null ?>

                    <?= $form->field($searchModel, 'city_id')->widget(Select2::className(), [
                        'initValueText' => $city ? $city->detailInfo : '',
                        'options' => [
                            'placeholder' => Yii::t('advertisement', 'Enter city name')
                        ],
                        'pluginOptions' => [
                            'allowClear' => true,
                            'minimumInputLength' => 2,
                            'ajax' => [
                                'url' => $getCityUrl,
                                'dataType' => 'json',
                                'data' => new JsExpression('function(params) { return {q:params.term}; }')
                            ],
                            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                            'templateResult' => new JsExpression('function(city) { return city.text; }'),
                            'templateSelection' => new JsExpression('function (city) { return city.text; }'),
                        ],
                    ])->label(false); ?>
                </div>
                <div class="col-xs-12" style="padding-bottom: 15px;">
                    <div class="row">
                        <div class="col-xs-12 col-md-2" style="padding-top: 5px;"><?= Yii::t('elevator', 'Distance from'); ?>:</div>
                        <div class="col-xs-12 col-md-10">
                            <input type="text"
                                   id="from_location"
                                   name="<?= $classname.'[from_location]'; ?>"
                                   value="<?= $searchModel->from_location; ?>"
                                   placeholder="<?= Yii::t('advertisement', 'Enter city name'); ?>"
                                   style="width: 100%"
                            >
                        </div>
                    </div>
                </div>

                <div class="col-xs-12" style="text-align: center; padding-bottom: 15px;">
                    <?php echo Html::submitButton(Yii::t('advertisement', 'Search'), ['class' => 'btn-green']) ?>
                    <a href="<?= Url::to(['map']); ?>" class="btn-green" style="">
                        <?= Yii::t('advertisement', 'Reset filter'); ?>
                    </a>
                </div>

                <div class="col-xs-12">
                    <div id="elevators_map" style="width: 100%; height: 600px; margin-bottom: 10px;"></div>
                </div>

                <?php $this->registerJs("var locations = ".$locations.";",
                    \yii\web\View::POS_HEAD,
                    'my-button-handler'
                ); ?>

                <div class="col-xs-12 rating-company ptb">
                    <?php foreach ($models as $model) { ?>
                        <?= $this->render('_elevator', ['model' => $model]); ?>
                    <?php } ?>
                </div>

                <div style="text-align: center">
                    <?php echo \yii\widgets\LinkPager::widget(['pagination' => $pages, 'registerLinkTags' => true]); ?>
                </div>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

frontend/modules/instruments/views/elevators/view.php
<?php
use yii\widgets\Breadcrumbs;
use frontend\assets\ElevatorAsset;
use backend\modules\elevator\models\ElevatorAccessibility;
use yii\helpers\Url;
ElevatorAsset::register($this);

$pageH1 = $model->title;
$this->title = $pageH1 .' | '.Yii::$app->params['titlePrefix'];
$this->registerMetaTag(['name'=>'description', 'content'=> $pageH1.' | '.Yii::$app->params['descriptionPrefix']]);
$this->registerLinkTag(['rel' => 'canonical', 'href' => Url::to(['view', 'alias' =>$model->alias])]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('instruments', 'Instruments'), 'url' => ['default/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('instruments', 'Elevators map'), 'url' => ['map']];
$this->params['breadcrumbs'][] = $pageH1;
?>

<div class="bread">
    <h1><?= $pageH1; ?></h1>
    <div class="bread-bg">
        <div class="container">
            <?= Breadcrumbs::widget(['links' => $this->params['breadcrumbs']]) ?>
        </div>
    </div>
</div>

<div class="container elevator-page" style="padding-top: 46px; padding-bottom: 46px;">
    <div class="row">
        <div class="col-xs-12 col-md-9">
            <?php if ($locations != 'false') { ?>
                <div class="row">
                    <div class="col-xs-12">
                        <div id="elevators_map" style="height: 400px; width: 100%"></div>
                    </div>
                    <p>&nbsp;</p>
                </div>
            <?php } ?>
            <?php $this->registerJs("var locations = ".$locations.";",
                \yii\web\View::POS_HEAD,
                'my-button-handler'
            ); ?>
            <div class="clearfix"></div>

            <?php $accessibilities = $model->accessibilities; ?>

            <?php if ($accessibilities || $model->volume || $model->loading || $model->unloading) { ?>
                <div class="col-xs-12 sales-product elevator-block">
                    <div class="col-sm-6" style="line-height: 100px;text-align: center;">
                        <?php foreach ($accessibilities as $one) { ?>
                            <?php if ($one->accessibility_id == ElevatorAccessibility::ACCESS_BY_CAR) { ?>
                                <img src="/images/auto.png" title="<?= Yii::t('elevator', 'Access by car'); ?>" alt="">
                            <?php } elseif ($one->accessibility_id == ElevatorAccessibility::ACCESS_BY_TRAIN) { ?>
                                <img src="/images/zd.png" title="<?= Yii::t('elevator', 'Access by train'); ?>" alt="">
                            <?php } elseif ($one->accessibility_id == ElevatorAccessibility::ACCESS_BY_BOAT) { ?>
                                <img src="/images/water.png" title="<?= Yii::t('elevator', 'Access by boat'); ?>" alt="">
                            <?php } ?>
                        <?php } ?>
                    </div>
                    <div class="col-sm-6" style="height: 100px;text-align: center; display: table">
                        <div style="display: table-cell; vertical-align: middle">
                            <span class="dsb">
                                <?php $volume = $model->volume ? ($model->volume . ' т') : Yii::t('common', 'No data'); ?>
                                <?= Yii::t('elevator', 'Warehouses'); ?>: <?= $volume; ?>
                            </span>
                            <span class="dsb">
                                <?php $loading = $model->loading ? ($model->loading . ' '.Yii::t('elevator', 't\day')) : Yii::t('common', 'No data'); ?>
                                <?= Yii::t('elevator', 'Elevator loading'); ?>: <?= $loading; ?>
                            </span>
                            <span class="dsb">
                                <?php $unloading = $model->unloading ? ($model->unloading . ' '.Yii::t('elevator', 't\day')) : Yii::t('common', 'No data'); ?>
                                <?= Yii::t('elevator', 'Elevator unloading'); ?>: <?= $unloading; ?>
                            </span>
                        </div>
                    </div>
                </div>
            <?php } ?>

            <div class="clearfix"></div>
            <div class="row">
                <div class="col-xs-12">
                    <div><?= $model->location; ?></div>
                    <?php if ($model->phones) { ?>
                        <div>Тел.: <?= $model->phones; ?></div>
                    <?php } ?>
                    <?php if ($model->email) { ?>
                        <div>Email: <?= $model->email; ?></div>
                    <?php } ?>
                    <?php if ($model->site) { ?>
                        <div>Сайт: <a href="<?= $model->site; ?>"><?= $model->site; ?></a></div>
                    <?php } ?>
                    <?php if ($model->property_type) { ?>
                        <div><?= $model->getAttributeLabel('property_type') . ': ' . $model->propertyTypeTitle; ?></div>
                    <?php } ?>
                    <?php if (is_numeric($model->laboratory)) { ?>
                        <div><?= $model->getAttributeLabel('laboratory') . ': ' . mb_strtolower($model->laboratoryTitle ? $model->laboratoryTitle : Yii::t('instrument/elevators', 'Нет данных')); ?></div>
                    <?php } ?>
                </div>
            </div>
            <div class="clearfix"></div>
            <?php $contacts = $model->contacts; ?>
            <?php if ($contacts) { ?>
                <div class="row" style="margin-top: 15px;">
                    <div class="col-xs-12">
                        <?php foreach ($contacts as $contact) { ?>
                            <div class="one-elevator-contact">
                                <div class="one-elevator-contact-title"><?= $contact->fio; ?></div>
                                <div class="one-elevator-contact-info">
                                    <div><?= 'тел.: ' . $contact->phones; ?></div>
                                    <?= $contact->email ? ('<div>email: '.$contact->email.'</div>') : ''; ?>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
                <div class="clearfix"></div>
            <?php } ?>
            <?php if ($model->additionalInfo) { ?>
                <div class="row">
                    <div class="col-xs-12">
                        <?= $model->additionalInfo; ?>
                    </div>
                </div>
                <div class="clearfix"></div>
            <?php } ?>
        </div>
        <div class="col-sm-3 sidebar-banner" style="margin-top: 0">
            <?=\backend\modules\advertising\widgets\AdvertisingWidget::widget(['key' => 'content', 'typePosition' => 'apeak']) ?>
        </div>
    </div>

</div>